### ISSUE TITLE
Create generic launch files for different cases of use.

### ISSUE THREAD

**Issue by Voldivh** [francocipollone/ros2_launch_examples#1]
## Summary
The objective of this issue is to create several launch files with examples of launch files. These files would have should have the basic information on how to use them for simple cases of use such as launch several nodes, components, process, etc. In addition to the cases told before, the examples should have enough information on how to use important functions such as substitutions, parameters, console arguments, etc.

The solution of this issue should be to create a launch file with it's own README file for each case of use (or perhaps combining altogether if possible) where it is shown the correct syntax/code for each case and the explanation of the code.

## Proposal: Examples to Create

- [x] Creation of launch descriptions with nodes, components and process.
- [x] Usage of substitutions, console arguments and ROS2 parameters
- [x] Parent launch files calling children launch files.
- [x] Combination of all the above
#2

**Comment by francocipollone** [comment]
Just as a comment, if the launch files provide enough documentation of what is happening (which is great to have in the example launch files) we could directly collapse all the cases into one example. I am saying this because the three 
```
- Creation of launch descriptions with nodes, components, and process.
- Usage of substitutions, console arguments, and ROS2 parameters
- Parent launch files calling children launch files.
```
Are kind of independent in their ways.
